apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smart-parrot
spec:
  replicas: 1
  template:
    metadata:
      name: smart-parrot
      labels:
        run: smart-parrot
    spec:
      containers:
        - name: smart-parrot
          image: "registry.ng.bluemix.net/<your-namespace>/smart-parrot"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /opt/lt-service-bind
              name: service-bind-volume
      volumes:
        - name: service-bind-volume
          secret:
            defaultMode: 420
            secretName: binding-mylanguagetranslator
---
apiVersion: v1
kind: Service
metadata:
  name: smart-parrot-service
  labels:
    run: smart-parrot
spec:
  type: NodePort
  selector:
    run: smart-parrot
  ports:
   - protocol: TCP
     port: 6001
     nodePort: 30801
